version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cs490_GP
    networks:
      - my_custom_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0
    depends_on:
      - mysql
    networks:
      - my_custom_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - my_custom_network
    healthcheck:
      test: curl -f http://localhost:3000 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  selenium:
    build:
      context: .
      dockerfile: Dockerfile.selenium
    depends_on:
      - frontend
      - backend
    volumes:
      - ./tests:/tests
    entrypoint: >
      sh -c "sleep 15 && pytest --disable-warnings /tests"
    environment:
      - FRONTEND_URL=http://localhost:3000Â  
      - BACKEND_URL=http://backend:5000
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
